"""
tests/load/locustfile.py — Load test for the Zero Trust Gateway.
Simulates 100 concurrent users exercising all service endpoints.
Measures OPA latency, request throughput, and deny rates.

Run with:
    locust -f tests/load/locustfile.py --host=http://localhost:8000 \
           --users=100 --spawn-rate=10 --run-time=60s --headless

Or open the Locust web UI:
    locust -f tests/load/locustfile.py --host=http://localhost:8000
"""
from __future__ import annotations

import json
import random
import time
from typing import Optional

from locust import HttpUser, TaskSet, between, events, task
from locust.clients import HttpSession

# ── Simulated client identities (CNs) ─────────────────────────────────────────
IDENTITIES = [
    "gateway.zerotrust.local",
    "service-a.zerotrust.local",
    "service-b.zerotrust.local",
    "monitoring.zerotrust.local",
    "admin-service.zerotrust.local",
]

INVALID_IDENTITIES = [
    "rogue.attacker.io",
    "unknown.service.local",
    "",
]


def random_cn(include_invalid: bool = False) -> str:
    """
    Return a random client CN for simulation.

    Args:
        include_invalid: If True, occasionally return an invalid CN.

    Returns:
        CN string.
    """
    if include_invalid and random.random() < 0.1:
        return random.choice(INVALID_IDENTITIES)
    return random.choice(IDENTITIES)


# ── Metrics accumulators ───────────────────────────────────────────────────────
_opa_latencies: list[float] = []
_denied_count = 0
_allowed_count = 0


@events.request.add_listener
def on_request(
    request_type, name, response_time, response_length, response, context, **kwargs
):
    """Track OPA latency from response headers and deny counts."""
    global _denied_count, _allowed_count
    if response is not None:
        if response.status_code == 403:
            _denied_count += 1
        elif response.status_code < 400:
            _allowed_count += 1
        # Track OPA latency if exposed via custom header
        opa_ms = response.headers.get("X-OPA-Latency-Ms")
        if opa_ms:
            try:
                _opa_latencies.append(float(opa_ms))
            except ValueError:
                pass


@events.test_stop.add_listener
def on_test_stop(environment, **kwargs):
    """Print OPA latency summary at end of load test."""
    if _opa_latencies:
        sorted_lat = sorted(_opa_latencies)
        n = len(sorted_lat)
        print("\n── OPA Latency Summary ──────────────────────────")
        print(f"  Samples:  {n}")
        print(f"  P50:      {sorted_lat[int(n * 0.50)]:.2f}ms")
        print(f"  P95:      {sorted_lat[int(n * 0.95)]:.2f}ms")
        print(f"  P99:      {sorted_lat[int(n * 0.99)]:.2f}ms")
        print(f"  Max:      {sorted_lat[-1]:.2f}ms")
    total = _denied_count + _allowed_count
    if total:
        deny_rate = (_denied_count / total) * 100
        print(f"\n── Authorization Summary ────────────────────────")
        print(f"  Allowed:  {_allowed_count}")
        print(f"  Denied:   {_denied_count}")
        print(f"  Deny rate: {deny_rate:.1f}%")


# ── Task Sets ──────────────────────────────────────────────────────────────────

class DataServiceTasks(TaskSet):
    """Tasks exercising Service B (Data Service) via the gateway."""

    @task(5)
    def get_records(self):
        """GET /records — most common operation (weight 5)."""
        cn = random.choice([
            "gateway.zerotrust.local",
            "service-a.zerotrust.local",
            "service-b.zerotrust.local",
        ])
        with self.client.get(
            "/records",
            headers={"X-Client-Cert-CN": cn},
            name="/records [GET]",
            catch_response=True,
        ) as resp:
            if resp.status_code not in {200, 403}:
                resp.failure(f"Unexpected status: {resp.status_code}")

    @task(2)
    def get_records_paginated(self):
        """GET /records with pagination params."""
        page = random.randint(1, 3)
        with self.client.get(
            f"/records?page={page}&page_size=5",
            headers={"X-Client-Cert-CN": "gateway.zerotrust.local"},
            name="/records [GET paginated]",
            catch_response=True,
        ) as resp:
            if resp.status_code not in {200, 403}:
                resp.failure(f"Unexpected status: {resp.status_code}")

    @task(2)
    def create_record(self):
        """POST /records — writer role required (gateway has it)."""
        with self.client.post(
            "/records",
            json={
                "title": f"Load Test Record {random.randint(1, 10000)}",
                "content": "Generated by Locust load test",
                "tags": ["load-test", "auto"],
            },
            headers={"X-Client-Cert-CN": "gateway.zerotrust.local"},
            name="/records [POST]",
            catch_response=True,
        ) as resp:
            if resp.status_code not in {201, 403}:
                resp.failure(f"Unexpected status: {resp.status_code}")

    @task(1)
    def unauthorized_post_attempt(self):
        """POST as service-a (reader only) — should get 403."""
        with self.client.post(
            "/records",
            json={"title": "Unauthorized Attempt", "content": "x"},
            headers={"X-Client-Cert-CN": "service-a.zerotrust.local"},
            name="/records [POST - unauthorized]",
            catch_response=True,
        ) as resp:
            if resp.status_code == 403:
                resp.success()  # 403 is expected
            elif resp.status_code == 201:
                resp.failure("Reader role should NOT be able to create records!")


class AuthServiceTasks(TaskSet):
    """Tasks exercising Service A (Auth Service) via the gateway."""

    @task(3)
    def verify_token(self):
        """GET /verify — any registered service can call this."""
        cn = random.choice(IDENTITIES)
        with self.client.get(
            "/verify",
            headers={
                "X-Client-Cert-CN": cn,
                "Authorization": "Bearer fake-test-token-for-load",
            },
            name="/verify [GET]",
            catch_response=True,
        ) as resp:
            if resp.status_code not in {200, 403}:
                resp.failure(f"Unexpected status: {resp.status_code}")

    @task(1)
    def login(self):
        """POST /login — only gateway can do this."""
        with self.client.post(
            "/login",
            json={"username": random.choice(["alice", "bob", "admin"]),
                  "password": "wrong-for-load-test"},
            headers={"X-Client-Cert-CN": "gateway.zerotrust.local"},
            name="/login [POST]",
            catch_response=True,
        ) as resp:
            # 401 (wrong password) or 200 are both valid from a routing perspective
            if resp.status_code not in {200, 401, 403}:
                resp.failure(f"Unexpected status: {resp.status_code}")


class HealthMetricsTasks(TaskSet):
    """Tasks for health and metrics endpoints."""

    @task(10)
    def health_check(self):
        """GET /health — highest frequency, no auth required."""
        with self.client.get(
            "/health",
            name="/health [GET]",
            catch_response=True,
        ) as resp:
            if resp.status_code != 200:
                resp.failure(f"Health check failed: {resp.status_code}")

    @task(3)
    def metrics(self):
        """GET /metrics — monitoring agent only."""
        with self.client.get(
            "/metrics",
            headers={"X-Client-Cert-CN": "monitoring.zerotrust.local"},
            name="/metrics [GET]",
            catch_response=True,
        ) as resp:
            if resp.status_code not in {200, 403}:
                resp.failure(f"Unexpected status: {resp.status_code}")


class DenialStormTasks(TaskSet):
    """Simulate a burst of unauthorized requests to measure OPA denial throughput."""

    @task(1)
    def unauthorized_admin_access(self):
        """Try to access service-c as non-admin — should always be 403."""
        cn = random.choice(["gateway.zerotrust.local", "service-a.zerotrust.local"])
        with self.client.get(
            "/users",
            headers={"X-Client-Cert-CN": cn},
            name="/users [GET - unauthorized]",
            catch_response=True,
        ) as resp:
            if resp.status_code == 403:
                resp.success()
            else:
                resp.failure(f"Expected 403 but got {resp.status_code}")

    @task(1)
    def no_cert_request(self):
        """Request with no CN — should always be 401."""
        with self.client.get(
            "/records",
            name="/records [GET - no cert]",
            catch_response=True,
        ) as resp:
            if resp.status_code == 401:
                resp.success()
            else:
                resp.failure(f"Expected 401 but got {resp.status_code}")


# ── User Classes ───────────────────────────────────────────────────────────────

class NormalUser(HttpUser):
    """
    Simulates a normal authenticated service making typical requests.
    Represents most of the traffic (weight=7).
    """
    weight = 7
    wait_time = between(0.1, 0.5)

    tasks = {
        DataServiceTasks: 6,
        AuthServiceTasks: 2,
        HealthMetricsTasks: 2,
    }


class MonitoringUser(HttpUser):
    """
    Simulates a monitoring agent checking health and metrics frequently.
    """
    weight = 2
    wait_time = between(1.0, 2.0)
    tasks = [HealthMetricsTasks]


class AttackerUser(HttpUser):
    """
    Simulates an attacker making unauthorized requests.
    Used to validate deny rate and OPA performance under denial load.
    """
    weight = 1
    wait_time = between(0.05, 0.2)
    tasks = [DenialStormTasks]
