#!/usr/bin/env bash
# setup_wireguard.sh — Idempotent WireGuard key generation and configuration
# Configures gateway (10.0.0.1), service-node (10.0.0.2), client (10.0.0.3)
set -euo pipefail

# ─── Colors ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; NC='\033[0m'; BOLD='\033[1m'

log_info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
log_success() { echo -e "${GREEN}[OK]${NC}    $*"; }
log_warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
log_error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }
log_step()    { echo -e "\n${BOLD}${BLUE}━━━ $* ━━━${NC}"; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KEYS_DIR="${SCRIPT_DIR}/keys"

# ─── Prerequisites ─────────────────────────────────────────────────────────────
check_prerequisites() {
    log_step "Checking Prerequisites"
    local missing=0
    for cmd in wg wg-quick iptables; do
        if command -v "$cmd" &>/dev/null; then
            log_success "$cmd found: $(command -v $cmd)"
        else
            log_error "$cmd not found. Install wireguard-tools."
            missing=1
        fi
    done
    [[ $missing -eq 1 ]] && { log_error "Missing prerequisites. Aborting."; exit 1; }
}

# ─── Key Generation ────────────────────────────────────────────────────────────
generate_keypair() {
    local node="$1"
    local privkey_file="${KEYS_DIR}/${node}_private.key"
    local pubkey_file="${KEYS_DIR}/${node}_public.key"

    if [[ -f "$privkey_file" && -f "$pubkey_file" ]]; then
        log_warn "Keys for ${node} already exist — skipping generation (idempotent)"
        return 0
    fi

    log_info "Generating keypair for ${node}..."
    wg genkey | tee "$privkey_file" | wg pubkey > "$pubkey_file"
    chmod 600 "$privkey_file"
    chmod 644 "$pubkey_file"
    log_success "Generated keys for ${node}"
}

generate_all_keys() {
    log_step "Generating WireGuard Keypairs"
    mkdir -p "$KEYS_DIR"
    chmod 700 "$KEYS_DIR"
    generate_keypair "gateway"
    generate_keypair "service-node"
    generate_keypair "client"
}

# ─── Config Generation ─────────────────────────────────────────────────────────
read_key() {
    cat "${KEYS_DIR}/${1}_${2}.key"
}

configure_gateway() {
    log_step "Configuring Gateway Node"
    local conf_file="${SCRIPT_DIR}/gateway/wg0.conf"

    local gw_priv; gw_priv=$(read_key gateway private)
    local sn_pub;  sn_pub=$(read_key service-node public)
    local cl_pub;  cl_pub=$(read_key client public)

    # Prompt for actual host addresses
    local sn_host="${SERVICE_NODE_HOST:-10.0.0.2}"
    local cl_host="${CLIENT_NODE_HOST:-10.0.0.3}"

    cat > "$conf_file" <<EOF
# WireGuard Configuration — Gateway Node (10.0.0.1)
# Auto-generated by setup_wireguard.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

[Interface]
PrivateKey = ${gw_priv}
Address = 10.0.0.1/24
ListenPort = 51820
DNS = 10.0.0.1

PostUp   = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE; iptables -A INPUT -p udp --dport 51820 -j ACCEPT
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE; iptables -D INPUT -p udp --dport 51820 -j ACCEPT

[Peer]
# Service Node
PublicKey = ${sn_pub}
AllowedIPs = 10.0.0.2/32
Endpoint = ${sn_host}:51820
PersistentKeepalive = 25

[Peer]
# Client Node
PublicKey = ${cl_pub}
AllowedIPs = 10.0.0.3/32
Endpoint = ${cl_host}:51820
PersistentKeepalive = 25
EOF
    chmod 600 "$conf_file"
    log_success "Gateway config written to ${conf_file}"
}

configure_service_node() {
    log_step "Configuring Service Node"
    local conf_file="${SCRIPT_DIR}/service-node/wg0.conf"

    local sn_priv; sn_priv=$(read_key service-node private)
    local gw_pub;  gw_pub=$(read_key gateway public)
    local gw_host="${GATEWAY_HOST:-10.0.0.1}"

    cat > "$conf_file" <<EOF
# WireGuard Configuration — Service Node (10.0.0.2)
# Auto-generated by setup_wireguard.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

[Interface]
PrivateKey = ${sn_priv}
Address = 10.0.0.2/24
ListenPort = 51820
DNS = 10.0.0.1

PostUp   = iptables -A INPUT -i wg0 -j ACCEPT; iptables -A INPUT -p tcp --dport 8001 -i eth0 -j DROP; iptables -A INPUT -p tcp --dport 8002 -i eth0 -j DROP; iptables -A INPUT -p tcp --dport 8003 -i eth0 -j DROP; iptables -A INPUT -p udp --dport 51820 -j ACCEPT
PostDown = iptables -D INPUT -i wg0 -j ACCEPT; iptables -D INPUT -p tcp --dport 8001 -i eth0 -j DROP; iptables -D INPUT -p tcp --dport 8002 -i eth0 -j DROP; iptables -D INPUT -p tcp --dport 8003 -i eth0 -j DROP; iptables -D INPUT -p udp --dport 51820 -j ACCEPT

[Peer]
# Gateway Node
PublicKey = ${gw_pub}
AllowedIPs = 10.0.0.0/24
Endpoint = ${gw_host}:51820
PersistentKeepalive = 25
EOF
    chmod 600 "$conf_file"
    log_success "Service Node config written to ${conf_file}"
}

configure_client() {
    log_step "Configuring Client Node"
    local conf_file="${SCRIPT_DIR}/client/wg0.conf"

    local cl_priv; cl_priv=$(read_key client private)
    local gw_pub;  gw_pub=$(read_key gateway public)
    local gw_host="${GATEWAY_HOST:-10.0.0.1}"

    cat > "$conf_file" <<EOF
# WireGuard Configuration — Client Node (10.0.0.3)
# Auto-generated by setup_wireguard.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

[Interface]
PrivateKey = ${cl_priv}
Address = 10.0.0.3/24
DNS = 10.0.0.1

PostUp   = iptables -A INPUT -i wg0 -j ACCEPT; iptables -A INPUT -p udp --dport 51820 -j ACCEPT
PostDown = iptables -D INPUT -i wg0 -j ACCEPT; iptables -D INPUT -p udp --dport 51820 -j ACCEPT

[Peer]
# Gateway Node
PublicKey = ${gw_pub}
AllowedIPs = 10.0.0.0/24
Endpoint = ${gw_host}:51820
PersistentKeepalive = 25
EOF
    chmod 600 "$conf_file"
    log_success "Client config written to ${conf_file}"
}

# ─── Interface Activation ──────────────────────────────────────────────────────
activate_interface() {
    local node="$1"
    local conf_dir="${SCRIPT_DIR}/${node}"

    log_step "Activating WireGuard Interface on ${node}"

    # Detect which node we're running on
    if ! ip link show wg0 &>/dev/null; then
        log_info "Bringing up wg0..."
        wg-quick up "${conf_dir}/wg0.conf"
        log_success "wg0 interface is UP"
    else
        log_warn "wg0 already exists — syncing config (idempotent)"
        wg syncconf wg0 <(wg-quick strip "${conf_dir}/wg0.conf")
        log_success "wg0 config synced"
    fi

    # Enable IP forwarding (required on gateway)
    if [[ "$node" == "gateway" ]]; then
        sysctl -w net.ipv4.ip_forward=1 > /dev/null
        echo "net.ipv4.ip_forward = 1" > /etc/sysctl.d/99-wireguard.conf
        log_success "IP forwarding enabled"
    fi
}

# ─── Print Summary ─────────────────────────────────────────────────────────────
print_summary() {
    log_step "Setup Complete"
    echo -e "${BOLD}Node Public Keys:${NC}"
    echo -e "  ${CYAN}Gateway:${NC}      $(read_key gateway public)"
    echo -e "  ${CYAN}Service Node:${NC} $(read_key service-node public)"
    echo -e "  ${CYAN}Client:${NC}       $(read_key client public)"
    echo ""
    echo -e "${GREEN}${BOLD}✓ WireGuard setup complete!${NC}"
    echo -e "  Run ${YELLOW}./check_tunnel.sh${NC} to verify connectivity."
}

# ─── Main ──────────────────────────────────────────────────────────────────────
main() {
    echo -e "${BOLD}${BLUE}"
    echo "╔══════════════════════════════════════════╗"
    echo "║   Zero Trust — WireGuard VPN Setup       ║"
    echo "╚══════════════════════════════════════════╝"
    echo -e "${NC}"

    check_prerequisites
    generate_all_keys
    configure_gateway
    configure_service_node
    configure_client

    # Activate only if --activate flag is passed
    if [[ "${1:-}" == "--activate" ]]; then
        local node="${2:-gateway}"
        activate_interface "$node"
    else
        log_info "Configs generated. Run with --activate <node> to bring up interface."
    fi

    print_summary
}

main "$@"
