#!/usr/bin/env bash
# teardown.sh — Idempotent clean removal of WireGuard configuration
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; NC='\033[0m'; BOLD='\033[1m'

log_info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
log_success() { echo -e "${GREEN}[OK]${NC}    $*"; }
log_warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
log_error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo -e "${BOLD}${RED}"
echo "╔══════════════════════════════════════════╗"
echo "║   Zero Trust — WireGuard Teardown        ║"
echo "╚══════════════════════════════════════════╝"
echo -e "${NC}"

# ─── Confirm unless --force ────────────────────────────────────────────────────
if [[ "${1:-}" != "--force" ]]; then
    echo -e "${YELLOW}WARNING: This will remove all WireGuard interfaces and configs.${NC}"
    read -rp "Continue? (yes/no): " CONFIRM
    [[ "$CONFIRM" != "yes" ]] && { log_info "Aborted."; exit 0; }
fi

# ─── Bring Down Interface ──────────────────────────────────────────────────────
log_info "Checking for active wg0 interface..."
if ip link show wg0 &>/dev/null; then
    log_info "Bringing down wg0..."
    # Try wg-quick first, fall back to ip link
    if wg-quick down wg0 2>/dev/null; then
        log_success "wg0 brought down via wg-quick"
    else
        ip link delete wg0 2>/dev/null && log_success "wg0 deleted via ip link" || \
            log_warn "Could not delete wg0 — may need root"
    fi
else
    log_warn "wg0 interface not found — already down (idempotent)"
fi

# ─── Remove iptables Rules ─────────────────────────────────────────────────────
log_info "Cleaning up iptables rules..."

# Remove rules if they exist (idempotent — errors are suppressed)
iptables -D FORWARD -i wg0 -j ACCEPT 2>/dev/null && log_success "Removed FORWARD -i wg0 rule" || true
iptables -D FORWARD -o wg0 -j ACCEPT 2>/dev/null && log_success "Removed FORWARD -o wg0 rule" || true
iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE 2>/dev/null && log_success "Removed NAT MASQUERADE rule" || true
iptables -D INPUT -p udp --dport 51820 -j ACCEPT 2>/dev/null && log_success "Removed UDP 51820 INPUT rule" || true
iptables -D INPUT -i wg0 -j ACCEPT 2>/dev/null && log_success "Removed INPUT -i wg0 rule" || true
iptables -D INPUT -p tcp --dport 8001 -i eth0 -j DROP 2>/dev/null && log_success "Removed block port 8001 rule" || true
iptables -D INPUT -p tcp --dport 8002 -i eth0 -j DROP 2>/dev/null && log_success "Removed block port 8002 rule" || true
iptables -D INPUT -p tcp --dport 8003 -i eth0 -j DROP 2>/dev/null && log_success "Removed block port 8003 rule" || true

# ─── Disable IP Forwarding ─────────────────────────────────────────────────────
log_info "Disabling IP forwarding..."
if [[ -f /etc/sysctl.d/99-wireguard.conf ]]; then
    rm -f /etc/sysctl.d/99-wireguard.conf
    sysctl -w net.ipv4.ip_forward=0 > /dev/null 2>&1 || true
    log_success "IP forwarding disabled"
else
    log_warn "No wireguard sysctl config found — skipping"
fi

# ─── Optionally Remove Keys ────────────────────────────────────────────────────
KEYS_DIR="${SCRIPT_DIR}/keys"
if [[ -d "$KEYS_DIR" ]]; then
    if [[ "${2:-}" == "--purge-keys" ]]; then
        log_info "Purging keys directory: ${KEYS_DIR}"
        rm -rf "$KEYS_DIR"
        log_success "Keys removed"
    else
        log_warn "Keys directory preserved at ${KEYS_DIR} (use --purge-keys to remove)"
    fi
fi

# ─── Remove Generated Configs ─────────────────────────────────────────────────
log_info "Checking generated configs..."
for conf in \
    "${SCRIPT_DIR}/gateway/wg0.conf" \
    "${SCRIPT_DIR}/service-node/wg0.conf" \
    "${SCRIPT_DIR}/client/wg0.conf"; do
    if [[ -f "$conf" ]]; then
        # Check if it was auto-generated (contains our timestamp comment)
        if grep -q "Auto-generated by setup_wireguard.sh" "$conf" 2>/dev/null; then
            rm -f "$conf"
            log_success "Removed generated config: $(basename $(dirname $conf))/wg0.conf"
        else
            log_warn "Skipping manually edited config: $conf"
        fi
    fi
done

echo ""
echo -e "${GREEN}${BOLD}✓ WireGuard teardown complete${NC}"
echo -e "  Run ${CYAN}./setup_wireguard.sh${NC} to reconfigure."
